### PR TITLE
feat: Confirm Dialog before deleting

### PR DESCRIPTION
**Pull request by Dhanus3133**
Confirm the user to delete with a dialog box

Fixes: #577
/claim #577

### CODE REVIEW

**Comment by maxgurewitz** [comment]
Amazing thank you for attempting this so quickly! I'll be sure to review before EOD tomorrow :) 🎆

**Comment by maxgurewitz** [comment]
Looks great but can you run `yarn workspace dashboard lint --fix` and push up the lint fixes!

**Review by maxgurewitz — CHANGES_REQUESTED** [review]
Looks great but can you run `yarn workspace dashboard lint --fix` and push up the lint fixes!

**Comment by Dhanus3133** [comment]
@maxgurewitz fixed it

**Comment by maxgurewitz** [comment]
@Dhanus3133 linting is still failing

```
./src/components/confirmDeleteDialog.tsx
19:51  Error: Function component is not a function declaration  react/function-component-definition
```

To check that linting succeeds. Run `yarn workspace dashboard lint`!

**Comment by Dhanus3133** [comment]
@maxgurewitz MB, check once again!

**Review by maxgurewitz — APPROVED** [review]

**Comment by maxgurewitz** [comment]
Done and Done!

**Pull request merged**
