### PR TITLE
DF-428 - Making user properties pane collapsible

### PR DESCRIPTION
**Pull request by ananthu-kurup**
Implemented the base requirements of DF-428 with all the correct icons being used.

As there have been some changes to the TemplateEditor page since the issue was originally created, I have had to make a few decisions w.r.t to icons for additional buttons in the new page.

#TODO: Warning showing existence of "Unpublished changes" needs to be thought through as there is no provision for that UX in this issue. Perhaps a warning icon can be used here.

### CODE REVIEW

**Review by maxgurewitz — COMMENTED** [review]
Hi @ananthu-kurup can you fix lint errors, and also make a screen recording of this feature? (I ask this of all contributors making frontend changes). Thanks!

**Comment by ananthu-kurup** [comment]
Hi @maxgurewitz, I have made a few more refinements to the implementation as well. Attaching a recording of the UI behaviour here. Also took care of the eslint errors.

There are a few things I am not too sure about:
- Is the padding around the icons and the border enough?
- Is there a more elegant solution to the "View Draft" toggle?


https://github.com/dittofeed/dittofeed/assets/16741492/71566420-35a9-4cf2-ac61-c9a84933c123

**Review by maxgurewitz — APPROVED** [review]
Looks great! Just fix the merge conflicts and we're ready to go! Thanks so much @ananthu-kurup

**Comment by ananthu-kurup** [comment]
Merge conflicts resolved. A few small changes were required post conflict resolution and they have been taken care of as well.

**Comment by chandlercraig** [comment]
@ananthu-kurup would you mind following the algora bot bounty claim instructions above? Once you do that, I'll be able to send payment. Thanks for your work on this!

**Pull request merged**
