### PR TITLE
Feat. ADD PERSISTENCE TO EVENTS TABLE PAGE STATE 

### LINKED ISSUE #637: [DF-436] persist event page search in url state
The url state state should include the page number, the page size, the searchTerm, and the currently selected event if there is one for the events table: `packages/dashboard/src/components/eventsTable.tsx`

<sub>From [SyncLinear.com](https://synclinear.com) | [DF-436](https://linear.app/dittofeed/issue/DF-436/persist-event-page-search-in-url-state)</sub>

### PR DESCRIPTION
**Pull request by hunxjunedo**
/fix #637 
/claim #637 
as can be seen in the following recordings, it now behaves as expected. The changes are:

- vigorously and fully tested with all testcases
- not breaking any existing features
- not difficult to understand or disturb the readability of code
- fully accompanied by comments throughout
- not dependant on any external library like react-router

@maxgurewitz this task wasn't an easy one, it was really time-consuming and complicated, especially the part which involved integrating the page param with existing MUI grid and Zustang state, without use of any other library. In my opinion the current bounty is extremely low for a task like this, **therefore I request a review on that, and request to raise it to a more reasonable amount.**  It will be appreciated.

[Screencast from 03-06-2024 21:47:22.webm](https://github.com/dittofeed/dittofeed/assets/89797440/4dfcd0c2-da84-4d58-9c84-2086038e508d)
[Screencast from 03-06-2024 20:27:33.webm](https://github.com/dittofeed/dittofeed/assets/89797440/36eceacc-d5c7-49b9-a171-7af7882fd15e)

EDIT: apologies for the lag in the recording.

### CODE REVIEW

**Comment by maxgurewitz** [comment]
Hi @hunxjunedo . You're right, this ticket is fairly complicated. We've had a few contributors attempt it and fail. This implementation also has some issues with it, that will take some time to work through. With that being said, I think the best course of action for now will be to close this issue and bounty. I feel that at this point this will be something I'll need to take on myself. 

I'm very sorry for wasting your time. I'd be happy to help you contribute to another, more manageable issue in the future.

**Comment by hunxjunedo** [comment]
I understand your concern, but it would be more helpful if you mentioned the issues with this solution, if they are other than the ones indicated by the automated test, as these are largely due to other files.

**Comment by maxgurewitz** [comment]
Hi @hunxjunedo the issue isn't the type warnings, it's with the overall approach of this implementation.

* You're not using the nextjs router.
* The way you're using setTimeout inside of a useEffect hook to set the table's state.

 Again, very sorry for wasting your time.

**Comment by hunxjunedo** [comment]
Got it, will be more than happy to contribute in the future.

**Pull request closed without merging**
