### PR TITLE
[feat]: search users by user property or segment value

### LINKED ISSUE #579: [DF-299] filter users by user property or segment value
Filter users by user property value or segment value e.g.

* user property - email:name
* segment - new users:true

Should be featured on the `/dashboard/users` page. Will likely require searching over the `computed_property_assignments_v2` clickhouse table, which will likely require a new skip index.

The filtering UX should be modeled after Linear's filtering, as shown below.

[https://www.loom.com/share/97674e0a0aea4c459f768fc21ea2199c?sid=da3456c0-e48b-4045-97e8-855b7d937330](https://www.loom.com/share/97674e0a0aea4c459f768fc21ea2199c?sid=da3456c0-e48b-4045-97e8-855b7d937330)

The `computed_property_assignments_v2`table should be queried by providing values for all columns in the sort key,

```
(workspace_id, type, computed_property_id, user_id)
```

<sub>From [SyncLinear.com](https://synclinear.com) | [DF-299](https://linear.app/dittofeed/issue/DF-299/filter-users-by-user-property-or-segment-value)</sub>

### PR DESCRIPTION
**Pull request by sy425191**
opening a draft PR so we can stay on the same page about the current progress in development.

- [ ] Updating UI of ```dashboard/users``` to include searching on the basis of `segments`  and `userProperty`
- [ ] populating list of segments and properties
- [ ] updating user api to handle 2 more parameters - propertyType and propertyValue
- [ ] indexing table for optimal performance

/fix #579 
/claim #579 

any suggestions would be appreciated

### CODE REVIEW

**Comment by maxgurewitz** [comment]
welcome @sy425191 !

**Comment by sy425191** [comment]
I'm pulling off myself from the issue, anyone from the community can take this issue. 

Reason: When I run project on localhost, my machine can't handle it coz its bulky, and on GitHub Codespaces: It fails to build, with some error in installing features on Devcontainer. I really wish if I could continue the development, but right now can't see any  way

**Comment by maxgurewitz** [comment]
@sy425191 dev containers have been fixed btw!

**Comment by sy425191** [comment]
@maxgurewitz That's great, dev containers really help

**Pull request closed without merging**
