### PR TITLE
Added support for custom headers

### PR DESCRIPTION
**Pull request by vikashsprem**
/claim #994
Fixes: #994

### CODE REVIEW

**Comment by vikashsprem** [comment]
@walseb Will it work? Please take a look.

**Comment by walseb** [comment]
Sure, I will try it. Thoughts @maxgurewitz?

**Comment by maxgurewitz** [comment]
I'll take a look! In the meantime, we ask that all PR's including frontend changes include a short screen recording demoing the feature. @vikashsprem Thank you!

**Comment by maxgurewitz** [comment]
Hi all, was gonna be hard to communicate the necessary work to get this over the finish line, so I issued a PR

https://github.com/dittofeed/dittofeed/pull/1022/files

**Pull request closed without merging**
